(* ::Package:: *)

(* ::Input:: *)
(*(*---------------------------------------------------------------------------------*)*)
(*(*---------------- Sandipan Dey, UMBC CSEE ----------------------------------------*)*)
(*(*---------------- The Source Code for Quantum Package-----------------------------*)*)
(*(*---------------- Functions --------------------------------------------------------*)
(*				1. ComputeOrthonormalEigenSpaces *)
(*                2. ComputeProjectors *)
(*                3. ComputeProbStates *)
(*			    4. ShowOutputTables*)
(*				5. MeasureQuantumSystem                 *)
(*-----------------------------------------------------------------------------*)*)
(**)
(*BeginPackage["QuantumBasic`"]*)
(**)
(*Begin["`Private`"]*)
(**)
(*Basis[n_] := IdentityMatrix[n];*)
(*Bra[k_, b_] := {b[[k + 1]]};*)
(*Ket[k_, b_] := Bra[k, b]\[ConjugateTranspose];*)
(*BraVec[coeff_, b_] := KetVec[coeff, b]\[ConjugateTranspose];*)
(*KetVec[coeff_, b_] := Module[{n, v, i},*)
(*	n = Dimensions[b][[1]]; v = Table[0, {i, n}, {j,1}]; Do [v = v + coeff[[i]] * Ket[i - 1, b], {i,n}]; v*)
(*];*)
(*InnerProduct[\[CapitalPsi]1_, \[CapitalPsi]2_] := \[CapitalPsi]1\[ConjugateTranspose].\[CapitalPsi]2;*)
(*InnerProductReal[\[CapitalPsi]1_, \[CapitalPsi]2_] := \[CapitalPsi]1\[Transpose].\[CapitalPsi]2;*)
(*TensorProduct[\[CapitalPsi]1_, \[CapitalPsi]2_] := KroneckerProduct[\[CapitalPsi]1,\[CapitalPsi]2];*)
(*TensorProduct[\[CapitalPsi]1_, \[CapitalPsi]2_, \[CapitalPsi]3_] := KroneckerProduct[KroneckerProduct[\[CapitalPsi]1,\[CapitalPsi]2],\[CapitalPsi]3];*)
(**)
(*TestBraKet[]:= Module[{b\[CapitalPsi], b\[CapitalPhi], b, k, c, d, \[CapitalPsi]1k, \[CapitalPsi]2b, \[CapitalPhi]1k, \[CapitalPhi]2b},*)
(**)
(*b\[CapitalPsi] = Basis[3];*)
(*b\[CapitalPhi] = Basis[4];*)
(**)
(*b = Bra[1, b\[CapitalPsi]]; Print[MatrixForm[b]];*)
(*k = Ket[2, b\[CapitalPsi]]; Print[MatrixForm[k]];*)
(*c = b.k; Print["<1|2>=", MatrixForm[c]];*)
(*d = k.b; Print["|1><2|=", MatrixForm[d]];*)
(**)
(*\[CapitalPsi]1k =  KetVec[{-2, -3I, I}, b\[CapitalPsi]]; Print[MatrixForm[\[CapitalPsi]1k]];*)
(*\[CapitalPsi]2b =  BraVec[{5, 7, 6I}, b\[CapitalPsi]] ; Print[MatrixForm[\[CapitalPsi]2b]];*)
(*\[CapitalPhi]1k =  KetVec[{I, 0, -2, 4}, b\[CapitalPhi]];Print[MatrixForm[\[CapitalPhi]1k]];*)
(*\[CapitalPhi]2b =  BraVec[{2, -5, 0, -7I}, b\[CapitalPhi]];Print[MatrixForm[\[CapitalPhi]2b]];*)
(*Print[MatrixForm[\[CapitalPsi]1k.\[CapitalPsi]2b] ]; Print[MatrixForm[\[CapitalPhi]1k.\[CapitalPhi]2b ]];*)
(*TensorProduct[\[CapitalPsi]1k.\[CapitalPsi]2b,\[CapitalPhi]1k.\[CapitalPhi]2b] // MatrixForm*)
(*];*)
(**)
(*TestBraKet[]*)
(**)
(*End[]*)
(**)
(*EndPackage[]*)
